apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.global.userAssignedIdentityClientID }}"
    keyvaultName: "{{ .Values.global.keyVaultName }}"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: database-connection-string
          objectType: secret
          objectVersion: ""
    tenantId: ""
  secretObjects:
    - secretName: db-secret-sync
      type: Opaque
      data:
        - objectName: database-connection-string
          key: DB_CONNECTION
